# Generated by Django 5.0.4 on 2024-05-10 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_alter_footballs_club'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footballs',
            name='club',
        ),
    ]
