# Generated by Django 5.0.4 on 2024-05-10 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_remove_footballs_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballs',
            name='club',
            field=models.ForeignKey(db_column='club', default=1, on_delete=django.db.models.deletion.CASCADE, to='teams.teams'),
            preserve_default=False,
        ),
    ]
