# Generated by Django 5.0.4 on 2024-05-10 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_countries_footballs_rating_alter_footballs_def_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Footballs',
            new_name='Footballers',
        ),
    ]
