# Generated by Django 5.0.4 on 2024-05-10 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_rename_footballs_footballers'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballers',
            name='country',
            field=models.ForeignKey(db_column='country', default=1, on_delete=django.db.models.deletion.CASCADE, to='teams.countries'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='countries',
            name='country',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
